                             (Eggless Red Velvet Cup Cake Recipe)

1. Preheat oven to 180 c. Line the muffin tray with paper cups.
2. Sieve together maida,cocoa powder, and soda bicarbonate.Soften butter in a bowl,add Nestle MILKMAID, and beat well.Add vanilla essence and mix.
3. Slowly fold in the sieved maida mixture and aerated soda alternately to the Milkmaid-Butter mix till all the maida mixture and soda are used up.Add the red colour and blend well. 
4. Pour the batter into the paper cups filling 3/4 of the cup and bake in the preheated oven for 15-20 minutes or till a toothpick insertedin the center of the cake comes out clean.
5. Remove from oven, coll for a while.Pipe the topping over the cakes and decorate.
6. Topping: Strain the dahi in a muslin cloth for 20 minutes to get hung curd.Plase the hung curd,Nestle MILKMAID, and butter in a bowl and beat together till thick.Spoon into an icing bag and pipe over the cool cakes.
